# Generated by Django 4.0.4 on 2022-04-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image_url',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
